fix healthcheck issue

diff --git a/Dockerfile.openswoole-vscode b/Dockerfile.openswoole-vscode
--- a/Dockerfile.openswoole-vscode
+++ b/Dockerfile.openswoole-vscode
@@ -219,6 +219,7 @@ RUN \
     docker-php-ext-install -j$(nproc) --ini-name zzz-docker-php-ext-openswoole.ini openswoole && \
     rm -f swoole.tar.gz $HOME/.composer/*-old.phar && \
     docker-php-source delete
+RUN npm install --save-dev chokidar
 
 # Clear npm proxy
 RUN npm config rm proxy
@@ -271,7 +272,7 @@ USER www-data
 
 COPY configs/supervisord-openswoole-vscode.conf /etc/supervisord.conf
 COPY configs/nginx.conf /etc/nginx/nginx.conf
-COPY configs/nginx-default.conf /etc/nginx/conf.d/default.conf
+COPY configs/nginx-default-octane.conf /etc/nginx/conf.d/default.conf
 COPY configs/index.php /var/www/html/public/index.php
 COPY configs/docker-vars.ini /usr/local/etc/php/conf.d/docker-vars.ini
 
@@ -281,4 +282,4 @@ USER root
 EXPOSE 80 9000 3000
 
 CMD ["/docker-entrypoint.sh"]
-#HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD healthcheck
+# HEALTHCHECK --start-period=5s --interval=2s --timeout=5s --retries=8 CMD php artisan octane:status || exit 1
